GET http://localhost:3001/api/blogs

###
DELETE http://localhost:3001/api/blogs/63c6c4faa91770218ca55d8d
###
POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "The Delta spirit",
    "author": "231Za",
    "url": "delta_blog.com",
    "likes": 18,
    "userId": "63c81328012deaa677d375dc"
}
###
POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "test2",
    "name": "Testing Test2",
    "password": "13141"
}
###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "test2",
    "password": "13141"
}
###