GET http://localhost:3001/api/blogs

###
DELETE http://localhost:3001/api/blogs/63c52fe464226d5e0259a687
###
POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "A Blog post today",
    "author": "Monka S",
    "url": "test.com",
    "likes": 128,
    "userId": "63ca8383a8d8ebff7ced2a3f"
}
###
POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "test3",
    "name": "Testing Test3",
    "password": "13141"
}
###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "test3",
    "password": "13141"
}
###